Fix sbuild-package to exit non-zero when appropriate.
It previously determined failure from the status file, as the pipe threw
sbuild's exit code away.

diff --git a/sbuild-package b/sbuild-package
--- a/sbuild-package
+++ b/sbuild-package
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Copyright 2009 Canonical Ltd.  This software is licensed under the
 # GNU Affero General Public License version 3 (see the file LICENSE).
@@ -12,6 +12,10 @@
 # Expects rest of arguments to be to pass to sbuild
 
 # Needs SBUILD to be set to a sbuild instance with passwordless sudo ability
+
+# We want a non-zero exit code from sbuild even if the implicit function
+# pointer check succeeds.
+set -o pipefail
 
 exec 2>&1
 
